/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di_calculadora.gui;

import di_calculadora.dto.Operacion;
import di_calculadora.logica.LogicaNegocio;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Herrero
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }
    
    private boolean validarOperacion(String operacionAValidar) {
        String patron = "(\\d+)[+-](\\d+)";
        return Pattern.matches(patron, operacionAValidar);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPanelBotones = new javax.swing.JPanel();
        botonCalculadoraTecla1 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla2 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla3 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTeclaAyuda = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla4 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla5 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla6 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTeclaBorrar = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla7 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla8 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla9 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTeclaLista = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTeclaSuma = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTecla0 = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTeclaResta = new botonCalculadora.BotonCalculadora();
        botonCalculadoraTeclaIgual = new botonCalculadora.BotonCalculadora();
        jPanelResultado = new javax.swing.JPanel();
        jTextFieldResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jPanelPanelBotones.setLayout(new java.awt.GridLayout(4, 4));

        botonCalculadoraTecla1.setText("1");
        botonCalculadoraTecla1.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla1.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla1.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla1.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla1ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla1);

        botonCalculadoraTecla2.setText("2");
        botonCalculadoraTecla2.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla2.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla2.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla2.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla2ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla2);

        botonCalculadoraTecla3.setText("3");
        botonCalculadoraTecla3.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla3.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla3.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla3.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla3ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla3);

        botonCalculadoraTeclaAyuda.setText("?");
        botonCalculadoraTeclaAyuda.setColorAlPasar(new java.awt.Color(255, 255, 0));
        botonCalculadoraTeclaAyuda.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTeclaAyuda.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTeclaAyuda.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanelPanelBotones.add(botonCalculadoraTeclaAyuda);

        botonCalculadoraTecla4.setText("4");
        botonCalculadoraTecla4.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla4.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla4.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla4.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla4ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla4);

        botonCalculadoraTecla5.setText("5");
        botonCalculadoraTecla5.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla5.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla5.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla5.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla5ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla5);

        botonCalculadoraTecla6.setText("6");
        botonCalculadoraTecla6.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla6.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla6.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla6.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla6ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla6);

        botonCalculadoraTeclaBorrar.setText("<");
        botonCalculadoraTeclaBorrar.setColorAlPasar(new java.awt.Color(255, 255, 0));
        botonCalculadoraTeclaBorrar.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTeclaBorrar.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTeclaBorrar.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTeclaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaBorrarActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTeclaBorrar);

        botonCalculadoraTecla7.setText("7");
        botonCalculadoraTecla7.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla7.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla7.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla7.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla7ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla7);

        botonCalculadoraTecla8.setText("8");
        botonCalculadoraTecla8.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla8.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla8.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla8.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla8ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla8);

        botonCalculadoraTecla9.setText("9");
        botonCalculadoraTecla9.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla9.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla9.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla9.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla9ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla9);

        botonCalculadoraTeclaLista.setText("Lista");
        botonCalculadoraTeclaLista.setColorAlPasar(new java.awt.Color(51, 255, 255));
        botonCalculadoraTeclaLista.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTeclaLista.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTeclaLista.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTeclaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaListaActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTeclaLista);

        botonCalculadoraTeclaSuma.setText("+");
        botonCalculadoraTeclaSuma.setColorAlPasar(new java.awt.Color(0, 255, 51));
        botonCalculadoraTeclaSuma.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTeclaSuma.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTeclaSuma.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTeclaSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaSumaActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTeclaSuma);

        botonCalculadoraTecla0.setText("0");
        botonCalculadoraTecla0.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla0.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTecla0.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTecla0.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTecla0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla0ActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTecla0);

        botonCalculadoraTeclaResta.setText("-");
        botonCalculadoraTeclaResta.setColorAlPasar(new java.awt.Color(0, 255, 51));
        botonCalculadoraTeclaResta.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTeclaResta.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTeclaResta.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTeclaResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaRestaActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTeclaResta);

        botonCalculadoraTeclaIgual.setText("=");
        botonCalculadoraTeclaIgual.setColorAlPasar(new java.awt.Color(0, 255, 51));
        botonCalculadoraTeclaIgual.setColorInicial(java.awt.Color.blue);
        botonCalculadoraTeclaIgual.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalculadoraTeclaIgual.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalculadoraTeclaIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaIgualActionPerformed(evt);
            }
        });
        jPanelPanelBotones.add(botonCalculadoraTeclaIgual);

        jTextFieldResultado.setEditable(false);
        jTextFieldResultado.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTextFieldResultado.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanelResultadoLayout = new javax.swing.GroupLayout(jPanelResultado);
        jPanelResultado.setLayout(jPanelResultadoLayout);
        jPanelResultadoLayout.setHorizontalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldResultado)
                .addContainerGap())
        );
        jPanelResultadoLayout.setVerticalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalculadoraTeclaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaListaActionPerformed
        PantallaLista pantallaLista = new PantallaLista(this, false);
        pantallaLista.setVisible(true);
    }//GEN-LAST:event_botonCalculadoraTeclaListaActionPerformed

    private void botonCalculadoraTecla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla1ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "1");
    }//GEN-LAST:event_botonCalculadoraTecla1ActionPerformed

    private void botonCalculadoraTecla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla2ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "2");

    }//GEN-LAST:event_botonCalculadoraTecla2ActionPerformed

    private void botonCalculadoraTecla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla3ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "3");

    }//GEN-LAST:event_botonCalculadoraTecla3ActionPerformed

    private void botonCalculadoraTecla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla4ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "4");

    }//GEN-LAST:event_botonCalculadoraTecla4ActionPerformed

    private void botonCalculadoraTecla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla5ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "5");

    }//GEN-LAST:event_botonCalculadoraTecla5ActionPerformed

    private void botonCalculadoraTecla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla6ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "6");

    }//GEN-LAST:event_botonCalculadoraTecla6ActionPerformed

    private void botonCalculadoraTecla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla7ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "7");

    }//GEN-LAST:event_botonCalculadoraTecla7ActionPerformed

    private void botonCalculadoraTecla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla8ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "8");

    }//GEN-LAST:event_botonCalculadoraTecla8ActionPerformed

    private void botonCalculadoraTecla9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla9ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "9");

    }//GEN-LAST:event_botonCalculadoraTecla9ActionPerformed

    private void botonCalculadoraTecla0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla0ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "0");

    }//GEN-LAST:event_botonCalculadoraTecla0ActionPerformed

    private void botonCalculadoraTeclaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaBorrarActionPerformed
        String cadenaOperacion = jTextFieldResultado.getText();
        jTextFieldResultado.setText(cadenaOperacion.substring(0, cadenaOperacion.length() -1));
    }//GEN-LAST:event_botonCalculadoraTeclaBorrarActionPerformed

    private void botonCalculadoraTeclaSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaSumaActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "+");
    }//GEN-LAST:event_botonCalculadoraTeclaSumaActionPerformed

    private void botonCalculadoraTeclaRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaRestaActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "-");
    }//GEN-LAST:event_botonCalculadoraTeclaRestaActionPerformed

    private void botonCalculadoraTeclaIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaIgualActionPerformed
        String cadenaOperacion = jTextFieldResultado.getText();
        
        if (cadenaOperacion.length() > 0) {
            if(validarOperacion(cadenaOperacion)){
                JOptionPane.showMessageDialog(this, "Se procede a guardar en la lista de operaciones", "Expresión correcta", JOptionPane.INFORMATION_MESSAGE);
                Operacion operacion = new Operacion();
                operacion.setOperacion(cadenaOperacion);
                
                SimpleDateFormat formateadorHora = new SimpleDateFormat("HH:mm:ss");
                Date fecha = new Date(Calendar.getInstance().getTimeInMillis());
                operacion.setFecha(fecha);
                String hora = formateadorHora.format(fecha);
                operacion.setHora(hora);
                
                LogicaNegocio.anadirOperacion(operacion);
                jTextFieldResultado.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Expresión incorrecta", "Error", JOptionPane.WARNING_MESSAGE);
            }
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Introduzca una operación", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_botonCalculadoraTeclaIgualActionPerformed
   
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla0;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla1;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla2;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla3;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla4;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla5;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla6;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla7;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla8;
    private botonCalculadora.BotonCalculadora botonCalculadoraTecla9;
    private botonCalculadora.BotonCalculadora botonCalculadoraTeclaAyuda;
    private botonCalculadora.BotonCalculadora botonCalculadoraTeclaBorrar;
    private botonCalculadora.BotonCalculadora botonCalculadoraTeclaIgual;
    private botonCalculadora.BotonCalculadora botonCalculadoraTeclaLista;
    private botonCalculadora.BotonCalculadora botonCalculadoraTeclaResta;
    private botonCalculadora.BotonCalculadora botonCalculadoraTeclaSuma;
    private javax.swing.JPanel jPanelPanelBotones;
    private javax.swing.JPanel jPanelResultado;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
