/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validacionExpresion.gui;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import validacionExpresion.dto.Expresion;
import validacionExpresion.logica.LogicaNegocio;

/**
 *
 * @author Pablo Herrero
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    PantallaDialogo pantallaDialogo = new PantallaDialogo(this, false);
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        try {
            cargarAyuda();
        } catch (MalformedURLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cargarAyuda() throws MalformedURLException, HelpSetException {
        // Carga el fichero de ayuda
        File fichero = new File("./help/help_set.hs");
        URL hsURL = fichero.toURI().toURL();
        // Crea el HelpSet y el HelpBroker
        HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
        HelpBroker hb = helpset.createHelpBroker();
        // Pone ayuda a item de menu al pulsarlo.
        hb.enableHelpOnButton(this.botonCalcuTeclaAyuda, "principal", helpset);
        hb.enableHelpKey(this.getContentPane(), "principal", helpset);
        hb.enableHelpKey(pantallaDialogo.getContentPane(), "lista", helpset);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCalcuTecla1 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla2 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla3 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTeclaAyuda = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla4 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla5 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla6 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTeclaBorrar = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla7 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla8 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla9 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTeclaLista = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTeclaSumar = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTecla0 = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTeclaRestar = new di_repaso_componentes_botonCalcu.BotonCalcu();
        botonCalcuTeclaIgual = new di_repaso_componentes_botonCalcu.BotonCalcu();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validación expresión");

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        botonCalcuTecla1.setText("1");
        botonCalcuTecla1.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla1.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla1.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla1.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla1);

        botonCalcuTecla2.setText("2");
        botonCalcuTecla2.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla2.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla2.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla2.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla2);

        botonCalcuTecla3.setText("3");
        botonCalcuTecla3.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla3.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla3.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla3.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla3);

        botonCalcuTeclaAyuda.setText("?");
        botonCalcuTeclaAyuda.setColorAlPasarEncima(java.awt.Color.yellow);
        botonCalcuTeclaAyuda.setColorInicial(java.awt.Color.blue);
        botonCalcuTeclaAyuda.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTeclaAyuda.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(botonCalcuTeclaAyuda);

        botonCalcuTecla4.setText("4");
        botonCalcuTecla4.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla4.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla4.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla4.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla4ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla4);

        botonCalcuTecla5.setText("5");
        botonCalcuTecla5.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla5.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla5.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla5.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla5ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla5);

        botonCalcuTecla6.setText("6");
        botonCalcuTecla6.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla6.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla6.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla6.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla6ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla6);

        botonCalcuTeclaBorrar.setText("<");
        botonCalcuTeclaBorrar.setColorAlPasarEncima(java.awt.Color.yellow);
        botonCalcuTeclaBorrar.setColorInicial(java.awt.Color.blue);
        botonCalcuTeclaBorrar.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTeclaBorrar.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTeclaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTeclaBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTeclaBorrar);

        botonCalcuTecla7.setText("7");
        botonCalcuTecla7.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla7.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla7.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla7.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla7ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla7);

        botonCalcuTecla8.setText("8");
        botonCalcuTecla8.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla8.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla8.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla8.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla8ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla8);

        botonCalcuTecla9.setText("9");
        botonCalcuTecla9.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla9.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla9.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla9.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla9ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla9);

        botonCalcuTeclaLista.setText("Lista");
        botonCalcuTeclaLista.setColorAlPasarEncima(new java.awt.Color(51, 204, 255));
        botonCalcuTeclaLista.setColorInicial(java.awt.Color.blue);
        botonCalcuTeclaLista.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTeclaLista.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTeclaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTeclaListaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTeclaLista);

        botonCalcuTeclaSumar.setText("+");
        botonCalcuTeclaSumar.setColorAlPasarEncima(java.awt.Color.green);
        botonCalcuTeclaSumar.setColorInicial(java.awt.Color.blue);
        botonCalcuTeclaSumar.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTeclaSumar.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTeclaSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTeclaSumarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTeclaSumar);

        botonCalcuTecla0.setText("0");
        botonCalcuTecla0.setColorAlPasarEncima(java.awt.Color.red);
        botonCalcuTecla0.setColorInicial(java.awt.Color.blue);
        botonCalcuTecla0.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTecla0.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTecla0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTecla0ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTecla0);

        botonCalcuTeclaRestar.setText("-");
        botonCalcuTeclaRestar.setColorAlPasarEncima(java.awt.Color.green);
        botonCalcuTeclaRestar.setColorInicial(java.awt.Color.blue);
        botonCalcuTeclaRestar.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTeclaRestar.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTeclaRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTeclaRestarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTeclaRestar);

        botonCalcuTeclaIgual.setText("=");
        botonCalcuTeclaIgual.setColorAlPasarEncima(java.awt.Color.green);
        botonCalcuTeclaIgual.setColorInicial(java.awt.Color.blue);
        botonCalcuTeclaIgual.setFuenteAlPasarEncima(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCalcuTeclaIgual.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        botonCalcuTeclaIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcuTeclaIgualActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcuTeclaIgual);

        jTextFieldResultado.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTextFieldResultado.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldResultado)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcuTeclaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTeclaListaActionPerformed
        pantallaDialogo.setVisible(true);
    }//GEN-LAST:event_botonCalcuTeclaListaActionPerformed

    private void botonCalcuTecla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla1ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "1");
    }//GEN-LAST:event_botonCalcuTecla1ActionPerformed

    private void botonCalcuTecla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla2ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "2");
    }//GEN-LAST:event_botonCalcuTecla2ActionPerformed

    private void botonCalcuTecla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla3ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "3");
    }//GEN-LAST:event_botonCalcuTecla3ActionPerformed

    private void botonCalcuTecla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla4ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "4");
    }//GEN-LAST:event_botonCalcuTecla4ActionPerformed

    private void botonCalcuTecla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla5ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "5");
    }//GEN-LAST:event_botonCalcuTecla5ActionPerformed

    private void botonCalcuTecla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla6ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "6");
    }//GEN-LAST:event_botonCalcuTecla6ActionPerformed

    private void botonCalcuTecla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla7ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "7");
    }//GEN-LAST:event_botonCalcuTecla7ActionPerformed

    private void botonCalcuTecla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla8ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "8");
    }//GEN-LAST:event_botonCalcuTecla8ActionPerformed

    private void botonCalcuTecla9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla9ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "9");
    }//GEN-LAST:event_botonCalcuTecla9ActionPerformed

    private void botonCalcuTecla0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTecla0ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "0");
    }//GEN-LAST:event_botonCalcuTecla0ActionPerformed

    private void botonCalcuTeclaSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTeclaSumarActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "+");
    }//GEN-LAST:event_botonCalcuTeclaSumarActionPerformed

    private void botonCalcuTeclaRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTeclaRestarActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "-");
    }//GEN-LAST:event_botonCalcuTeclaRestarActionPerformed

    private void botonCalcuTeclaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTeclaBorrarActionPerformed
        String operacion = jTextFieldResultado.getText();
        jTextFieldResultado.setText(operacion.substring(0, operacion.length()-1));
    }//GEN-LAST:event_botonCalcuTeclaBorrarActionPerformed

    private void botonCalcuTeclaIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcuTeclaIgualActionPerformed
        String operacion = jTextFieldResultado.getText();
        if(operacion.length() > 0) {
            if(isOperacion(operacion)) {
                JOptionPane.showMessageDialog(this, "Se procede a guardar en la lista de operaciones", "Expresión correcta", JOptionPane.INFORMATION_MESSAGE);
                Expresion expresion = new Expresion();
                Date fecha = new Date();
                SimpleDateFormat formateadorHora = new SimpleDateFormat("HH:mm:ss");
                String hora = formateadorHora.format(fecha);
                
                expresion.setFecha(fecha);
                expresion.setHora(hora);
                expresion.setOperacion(operacion);
                LogicaNegocio.aniadirExpresion(expresion);
                
                jTextFieldResultado.setText("");
            }else {
                JOptionPane.showMessageDialog(this, "Expresión incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Ingrese una operación válida");
        }
    }//GEN-LAST:event_botonCalcuTeclaIgualActionPerformed

    private boolean isOperacion(String operacion) {
        String patron = "(\\d+[+-/*]\\d+)(([+-/*]\\d+)+)?";
        Pattern pattern = Pattern.compile(patron);
        Matcher matcher = pattern.matcher(operacion);
        return matcher.matches();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.easynth.lookandfeel.EaSynthLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla0;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla1;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla2;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla3;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla4;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla5;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla6;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla7;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla8;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTecla9;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTeclaAyuda;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTeclaBorrar;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTeclaIgual;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTeclaLista;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTeclaRestar;
    private di_repaso_componentes_botonCalcu.BotonCalcu botonCalcuTeclaSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
