/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di_gestionClientesExamen.gui;

import di_gestionClientesExamen.dto.Cliente;
import di_gestionClientesExamen.logica.LogicaNegocio;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Herrero
 */
public class PantallaInsertar extends javax.swing.JDialog {

    private PantallaPrincipal pantallaPrincipal;

    /**
     * Creates new form PantallaInsertar
     */
    public PantallaInsertar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldGestionClientesDNI = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesNombre = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesDireccion = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesApellidos = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesLocalidad = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesProvincia = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesCP = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesTelefono = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jTextFieldGestionClientesEmail = new di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar");
        setResizable(false);

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Provincia:");

        jLabel6.setText("Localidad:");

        jLabel7.setText("C.P.:");

        jLabel8.setText("Teléfono:");

        jLabel9.setText("EMail:");

        jTextFieldGestionClientesDNI.setLongitud(9);

        jTextFieldGestionClientesNombre.setLongitud(25);

        jTextFieldGestionClientesDireccion.setLongitud(50);

        jTextFieldGestionClientesApellidos.setLongitud(35);

        jTextFieldGestionClientesLocalidad.setLongitud(30);

        jTextFieldGestionClientesProvincia.setLongitud(20);

        jTextFieldGestionClientesCP.setEs_numerico(true);
        jTextFieldGestionClientesCP.setLongitud(5);

        jTextFieldGestionClientesTelefono.setEs_numerico(true);
        jTextFieldGestionClientesTelefono.setLongitud(9);

        jTextFieldGestionClientesEmail.setLongitud(30);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha inicio:");

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldGestionClientesTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGestionClientesEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldGestionClientesDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGestionClientesApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldGestionClientesProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(jTextFieldGestionClientesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldGestionClientesLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldGestionClientesCP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jTextFieldGestionClientesDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldGestionClientesDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldGestionClientesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldGestionClientesApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldGestionClientesDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldGestionClientesLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGestionClientesProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGestionClientesCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldGestionClientesTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGestionClientesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String dni = jTextFieldGestionClientesDNI.getText();
        String nombre = jTextFieldGestionClientesNombre.getText();
        String apellidos = jTextFieldGestionClientesApellidos.getText();
        Date fecha = (Date) jSpinnerFecha.getValue();
        String direccion = jTextFieldGestionClientesDireccion.getText();
        String localidad = jTextFieldGestionClientesLocalidad.getText();
        String provincia = jTextFieldGestionClientesProvincia.getText();
        String cp = jTextFieldGestionClientesCP.getText();
        String telefono = jTextFieldGestionClientesTelefono.getText();
        String email = jTextFieldGestionClientesEmail.getText();
        
        if (validarFormulario()) {
            Cliente cliente = new Cliente();
            cliente.setDni(dni);
            cliente.setNombre(nombre);
            cliente.setApellidos(apellidos);
            cliente.setFechaInicio(fecha);
            cliente.setDireccion(direccion);
            cliente.setLocalidad(localidad);
            cliente.setProvincia(provincia);
            cliente.setCp(cp);
            cliente.setTelefono(telefono);
            cliente.setEmail(email);
            
            LogicaNegocio.anadirCliente(cliente);

            JOptionPane.showMessageDialog(this, "Cliente insertado", "", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            jTextFieldGestionClientesDNI.setText("");
            jTextFieldGestionClientesNombre.setText("");
            jTextFieldGestionClientesApellidos.setText("");
            jTextFieldGestionClientesDireccion.setText("");
            jTextFieldGestionClientesLocalidad.setText("");
            jTextFieldGestionClientesProvincia.setText("");
            jTextFieldGestionClientesCP.setText("");
            jTextFieldGestionClientesTelefono.setText("");
            jTextFieldGestionClientesEmail.setText("");
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private boolean validarFormulario() {
        boolean flag = true;

        if ((jTextFieldGestionClientesNombre.getText().isEmpty()) || 
                ("".equals(jTextFieldGestionClientesNombre.getText()))) {
            JOptionPane.showMessageDialog(this, "Campo NOMBRE requerido", "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return flag = false;
        }

        if ((jTextFieldGestionClientesApellidos.getText().isEmpty()) || 
                ("".equals(jTextFieldGestionClientesApellidos.getText()))) {
            JOptionPane.showMessageDialog(this, "Campo APELLIDOS requerido", "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return flag = false;
        }

        if ((jTextFieldGestionClientesDNI.getText().isEmpty()) || 
                ("".equals(jTextFieldGestionClientesDNI.getText())) || 
                !isDNI(jTextFieldGestionClientesDNI.getText())) {
            JOptionPane.showMessageDialog(this, "DNI erróneo.", "Error", JOptionPane.WARNING_MESSAGE);
            return flag = false;
        }

        if ((jTextFieldGestionClientesEmail.getText().isEmpty()) || 
                ("".equals(jTextFieldGestionClientesEmail.getText())) || 
                !isEmail(jTextFieldGestionClientesEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Email erróneo.", "Error", JOptionPane.WARNING_MESSAGE);
            return flag = false;
        }
        return flag;
    }

    private boolean isDNI(String dni) {
        String patronDNI = "^[0-9]{8}[T|R|W|A|G|M|Y|F|P|D|X|B|N|J|Z|S|Q|V|H|L|C|K|E]$";
        Pattern pattern = Pattern.compile(patronDNI);
        Matcher matcher = pattern.matcher(dni);
        System.out.println(matcher.matches());
        return matcher.matches();
    }

    private boolean isEmail(String email) {
        String patronDNI = "^[\\w-]+(\\.[\\w-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern = Pattern.compile(patronDNI);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaInsertar dialog = new PantallaInsertar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerFecha;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesApellidos;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesCP;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesDNI;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesDireccion;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesEmail;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesLocalidad;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesNombre;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesProvincia;
    private di_componentegestionclientes_jMenuGestionClientes.JTextFieldGestionClientes jTextFieldGestionClientesTelefono;
    // End of variables declaration//GEN-END:variables
}
