/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validacionExpresion.gui;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import validacionExpresion.dto.Expresion;
import validacionExpresion.logica.LogicaNegocio;

/**
 *
 * @author Pablo Herrero
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    PantallaLista pantallaLista;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        pantallaLista = new PantallaLista(this, false);
        try {
            cargarAyuda();
        } catch (HelpSetException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarAyuda() throws HelpSetException, MalformedURLException {
        // Carga el fichero de ayuda
        File fichero = new File("./help/help_set.hs");
        URL hsURL = fichero.toURI().toURL();
        // Crea el HelpSet y el HelpBroker
        HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
        HelpBroker hb = helpset.createHelpBroker();
        // Pone ayuda a item de menu al pulsarlo.
        hb.enableHelpOnButton(botonCalculadoraTeclaAyuda, "ventana_principal", helpset);    // Botón ayuda en pantalla principal
        hb.enableHelpKey(this.getContentPane(), "ventana_principal", helpset);              // Tecla f1 en pantalla principal
        hb.enableHelpKey(pantallaLista.getContentPane(), "ventana_lista", helpset);         // Tecla F1 en pantalla lista

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTeclado = new javax.swing.JPanel();
        botonCalculadoraTecla1 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla2 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla3 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTeclaAyuda = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla4 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla5 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla6 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTeclaBorrar = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla7 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla8 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla9 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTeclaLista = new botoncalculadora.botonCalculadora();
        botonCalculadoraTeclaSuma = new botoncalculadora.botonCalculadora();
        botonCalculadoraTecla0 = new botoncalculadora.botonCalculadora();
        botonCalculadoraTeclaResta = new botoncalculadora.botonCalculadora();
        botonCalculadoraTeclaIgual = new botoncalculadora.botonCalculadora();
        jPanelResultado = new javax.swing.JPanel();
        jTextFieldResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validación expresión APP");

        jPanelTeclado.setLayout(new java.awt.GridLayout(4, 4));

        botonCalculadoraTecla1.setText("1");
        botonCalculadoraTecla1.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla1.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla1.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla1.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla1ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla1);

        botonCalculadoraTecla2.setText("2");
        botonCalculadoraTecla2.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla2.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla2.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla2.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla2ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla2);

        botonCalculadoraTecla3.setText("3");
        botonCalculadoraTecla3.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla3.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla3.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla3.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla3ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla3);

        botonCalculadoraTeclaAyuda.setText("?");
        botonCalculadoraTeclaAyuda.setColorAlPasar(java.awt.Color.yellow);
        botonCalculadoraTeclaAyuda.setColorInicial(java.awt.Color.black);
        botonCalculadoraTeclaAyuda.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaAyuda.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanelTeclado.add(botonCalculadoraTeclaAyuda);

        botonCalculadoraTecla4.setText("4");
        botonCalculadoraTecla4.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla4.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla4.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla4.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla4ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla4);

        botonCalculadoraTecla5.setText("5");
        botonCalculadoraTecla5.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla5.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla5.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla5.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla5ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla5);

        botonCalculadoraTecla6.setText("6");
        botonCalculadoraTecla6.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla6.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla6.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla6.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla6ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla6);

        botonCalculadoraTeclaBorrar.setText("<");
        botonCalculadoraTeclaBorrar.setColorAlPasar(java.awt.Color.yellow);
        botonCalculadoraTeclaBorrar.setColorInicial(java.awt.Color.black);
        botonCalculadoraTeclaBorrar.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaBorrar.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaBorrarActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTeclaBorrar);

        botonCalculadoraTecla7.setText("7");
        botonCalculadoraTecla7.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla7.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla7.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla7.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla7ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla7);

        botonCalculadoraTecla8.setText("8");
        botonCalculadoraTecla8.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla8.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla8.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla8.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla8ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla8);

        botonCalculadoraTecla9.setText("9");
        botonCalculadoraTecla9.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla9.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla9.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla9.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla9ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla9);

        botonCalculadoraTeclaLista.setText("Lista");
        botonCalculadoraTeclaLista.setColorAlPasar(java.awt.Color.blue);
        botonCalculadoraTeclaLista.setColorInicial(java.awt.Color.black);
        botonCalculadoraTeclaLista.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaLista.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaListaActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTeclaLista);

        botonCalculadoraTeclaSuma.setText("+");
        botonCalculadoraTeclaSuma.setColorAlPasar(java.awt.Color.green);
        botonCalculadoraTeclaSuma.setColorInicial(java.awt.Color.black);
        botonCalculadoraTeclaSuma.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaSuma.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaSumaActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTeclaSuma);

        botonCalculadoraTecla0.setText("0");
        botonCalculadoraTecla0.setColorAlPasar(java.awt.Color.red);
        botonCalculadoraTecla0.setColorInicial(java.awt.Color.black);
        botonCalculadoraTecla0.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla0.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTecla0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTecla0ActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTecla0);

        botonCalculadoraTeclaResta.setText("-");
        botonCalculadoraTeclaResta.setColorAlPasar(java.awt.Color.green);
        botonCalculadoraTeclaResta.setColorInicial(java.awt.Color.black);
        botonCalculadoraTeclaResta.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaResta.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaRestaActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTeclaResta);

        botonCalculadoraTeclaIgual.setText("=");
        botonCalculadoraTeclaIgual.setColorAlPasar(java.awt.Color.green);
        botonCalculadoraTeclaIgual.setColorInicial(java.awt.Color.black);
        botonCalculadoraTeclaIgual.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaIgual.setFuenteInicial(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        botonCalculadoraTeclaIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculadoraTeclaIgualActionPerformed(evt);
            }
        });
        jPanelTeclado.add(botonCalculadoraTeclaIgual);

        jPanelResultado.setLayout(new java.awt.CardLayout());

        jTextFieldResultado.setEditable(false);
        jTextFieldResultado.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTextFieldResultado.setForeground(new java.awt.Color(0, 51, 204));
        jPanelResultado.add(jTextFieldResultado, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalculadoraTecla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla1ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "1");
    }//GEN-LAST:event_botonCalculadoraTecla1ActionPerformed

    private void botonCalculadoraTecla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla2ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "2");
    }//GEN-LAST:event_botonCalculadoraTecla2ActionPerformed

    private void botonCalculadoraTecla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla3ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "3");
    }//GEN-LAST:event_botonCalculadoraTecla3ActionPerformed

    private void botonCalculadoraTecla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla4ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "4");
    }//GEN-LAST:event_botonCalculadoraTecla4ActionPerformed

    private void botonCalculadoraTecla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla5ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "5");
    }//GEN-LAST:event_botonCalculadoraTecla5ActionPerformed

    private void botonCalculadoraTecla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla6ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "6");
    }//GEN-LAST:event_botonCalculadoraTecla6ActionPerformed

    private void botonCalculadoraTecla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla7ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "7");
    }//GEN-LAST:event_botonCalculadoraTecla7ActionPerformed

    private void botonCalculadoraTecla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla8ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "8");
    }//GEN-LAST:event_botonCalculadoraTecla8ActionPerformed

    private void botonCalculadoraTecla9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla9ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "9");

    }//GEN-LAST:event_botonCalculadoraTecla9ActionPerformed

    private void botonCalculadoraTecla0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTecla0ActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "0");
    }//GEN-LAST:event_botonCalculadoraTecla0ActionPerformed

    private void botonCalculadoraTeclaSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaSumaActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "+");
    }//GEN-LAST:event_botonCalculadoraTeclaSumaActionPerformed

    private void botonCalculadoraTeclaRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaRestaActionPerformed
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "-");
    }//GEN-LAST:event_botonCalculadoraTeclaRestaActionPerformed

    private void botonCalculadoraTeclaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaBorrarActionPerformed
        String cadena = jTextFieldResultado.getText();
        jTextFieldResultado.setText(cadena.substring(0, cadena.length() - 1));
    }//GEN-LAST:event_botonCalculadoraTeclaBorrarActionPerformed

    private void botonCalculadoraTeclaIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaIgualActionPerformed
        String operacionAValidar = jTextFieldResultado.getText();
        // Valido usando método propio (está debajo de los actionPerformed)
        if (validarExpresion(operacionAValidar)) {
            // Si valida, asigno valores a la expresión que voy a almacenar
            Expresion expresion = new Expresion();
            Date fecha = new Date();
            SimpleDateFormat formateadorHora = new SimpleDateFormat("HH:mm:ss");
            String hora = formateadorHora.format(fecha);

            expresion.setFecha(fecha);
            expresion.setHora(hora);
            expresion.setOperacion(operacionAValidar);

            // Añado a la lista y muestro el mensaje de confirmación
            LogicaNegocio.aniadirExpresion(expresion);
            JOptionPane.showMessageDialog(this, "Se procede a guardar en la lista de operaciones", "Expresión correcta", JOptionPane.INFORMATION_MESSAGE);

            // Limpio el campo para dejarlo listo para la siguiente operación
            jTextFieldResultado.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Expresión incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCalculadoraTeclaIgualActionPerformed

    private void botonCalculadoraTeclaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculadoraTeclaListaActionPerformed
        pantallaLista.setVisible(true);
    }//GEN-LAST:event_botonCalculadoraTeclaListaActionPerformed

    private boolean validarExpresion(String expresionAValidar) {
        String patron = "(\\d+[+-/*]\\d+)(([+-/*]\\d+)+)?";
        Pattern pattern = Pattern.compile(patron);
        Matcher matcher = pattern.matcher(expresionAValidar);
        return matcher.matches();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.easynth.lookandfeel.EaSynthLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botoncalculadora.botonCalculadora botonCalculadoraTecla0;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla1;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla2;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla3;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla4;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla5;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla6;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla7;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla8;
    private botoncalculadora.botonCalculadora botonCalculadoraTecla9;
    private botoncalculadora.botonCalculadora botonCalculadoraTeclaAyuda;
    private botoncalculadora.botonCalculadora botonCalculadoraTeclaBorrar;
    private botoncalculadora.botonCalculadora botonCalculadoraTeclaIgual;
    private botoncalculadora.botonCalculadora botonCalculadoraTeclaLista;
    private botoncalculadora.botonCalculadora botonCalculadoraTeclaResta;
    private botoncalculadora.botonCalculadora botonCalculadoraTeclaSuma;
    private javax.swing.JPanel jPanelResultado;
    private javax.swing.JPanel jPanelTeclado;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
